### ISSUE TITLE
Create and finish frontend layout

### ISSUE THREAD

**Issue by mhorst00** [mhorst00/vvs-mining#12]
Document existing and upcoming progress of the frontend layouting here.

**Comment by Blackcheckgamer** [comment]
-  Verspätungsinfos Tab
- [ ] Dummy Table
- [ ] Station Filter
- [ ] Train Filter
- [ ] Time filter (Full)
- [ ] Time filter (Day)
- [ ] Time filter (Timeframe)

- Haltestelleninfos Tab
- Verspätungen für Linien Tab
- Verspätungen für Stationen Tab
- Verspätungskarte Tab

**Comment by mhorst00** [comment]
Overall ToDos:

- [ ] Switch tables to [these](https://github.com/vincjo/datatables) datatables for search, sort and pagination
